### ISSUE TITLE
Apache License should not include the copyright information

### ISSUE THREAD

**Issue by WillemJiang** [EdgeGallery/infra#21]
As we add the copyright information on the License header of the source code.
Current Apache License should not include the copyright information like [this]( https://github.com/EdgeGallery/mep/blob/e3e415aac10978fddd687fd0b227dc74d475d6f9/LICENSE#L189 )

**Comment by zhangbeiyuan-hw** [comment]
Fixed, the license file in mep and mep-agent has been updated.

**Comment by WillemJiang** [comment]
It‘s a common issue on the other repos.  Could you update them all?
